# Generated by Django 5.2.1 on 2025-05-16 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UniversityCampus',
        ),
    ]
